# Generated by Django 4.2.11 on 2024-05-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_question_choices_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question', verbose_name='Следующий вопрос'),
        ),
    ]
