# Generated by Django 4.2.11 on 2024-05-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_survey_options_usersurvey_last_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Следующий вопрос', 'verbose_name_plural': 'Следующий вопрос'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результаты опросов'},
        ),
        migrations.AlterModelOptions(
            name='usersurvey',
            options={'verbose_name': 'Завершенный опрос', 'verbose_name_plural': 'Завершенные опросы'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_list', to='survey.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='survey.choice', verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question', verbose_name='Следующий вопрос'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='first_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_surveys', to='survey.question', verbose_name='Первый вопрос'),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='last_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.answer', verbose_name='Последний ответ'),
        ),
    ]
