# Generated by Django 4.2.11 on 2024-05-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_answer_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='next_question',
        ),
    ]
