# Generated by Django 4.2.11 on 2024-05-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_question_next_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='first_question',
        ),
    ]
