# Generated by Django 4.2.11 on 2024-05-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_survey_first_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
