# Generated by Django 4.2.11 on 2024-05-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_question_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='last_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.choice', verbose_name='Последний ответ'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
