# Generated by Django 4.2.11 on 2024-05-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_usersurvey_last_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Ответ')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_answers', to='survey.question', verbose_name='Следующий вопрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Следующий вопрос',
                'verbose_name_plural': 'Следующий вопрос',
            },
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='last_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.answer', verbose_name='Последний ответ'),
        ),
    ]
