# Generated by Django 4.2.11 on 2024-05-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_alter_usersurvey_last_answer_delete_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
