# Generated by Django 4.2.11 on 2024-05-11 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0015_rename_usersurvey_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UserSurvey',
        ),
    ]
